# Generated by Django 4.1.7 on 2023-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
