# Generated by Django 4.1.7 on 2023-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_blacklisttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
    ]
