# Generated by Django 4.1.7 on 2023-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_connect',
            field=models.IntegerField(default=0),
        ),
    ]
