# Generated by Django 4.1.7 on 2023-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_number_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_pressure',
            field=models.IntegerField(default=0),
        ),
    ]
