# Generated by Django 4.1.7 on 2023-05-18 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_treatment_doctor_alter_treatment_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='vitalss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
