# Generated by Django 4.1.7 on 2023-06-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisttoken',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
