# Generated by Django 4.1.7 on 2023-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalss',
            name='c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vitalss',
            name='d',
            field=models.IntegerField(default=0),
        ),
    ]
