# Generated by Django 4.1.7 on 2023-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_vitalss_c_vitalss_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cholesterol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fbs',
            field=models.IntegerField(default=0),
        ),
    ]
