# Generated by Django 4.1.7 on 2023-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.ImageField(blank=True, null=True, upload_to='diplomas')),
                ('dipmoma_status', models.CharField(default='untreated', max_length=20)),
                ('is_approved', models.BooleanField(default=0)),
            ],
        ),
    ]
